### ISSUE TITLE
Error while gathering completions

### ISSUE THREAD

**Issue by epeli** [autozimu/LanguageClient-neovim#120]
Hi, I'm getting following error from LanguageClient/deoplete when using `felixfbecker/php-language-server`. However I'm not seeing this with Typescript and `sourcegraph/javascript-typescript-langserver`.

```
[deoplete] Error while gathering completions.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 52, in completion_begin
[deoplete]     self.gather_results(context), context['input'])
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 165, in merge_results
[deoplete]     result['context'])
[deoplete]   File "/var/www/git/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 81, in gather_candidates
[deoplete]     for item in items]
[deoplete]   File "/var/www/git/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 81, in <listcomp>
[deoplete]     for item in items]
[deoplete]   File "/var/www/git/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 47, in convertToDeopleteCandidate
[deoplete]     word = item["textEdit"].get("newText", word)
[deoplete] AttributeError: 'NoneType' object has no attribute 'get'
[deoplete] Error while gathering completions.  Use :messages for error details.
```

- neovim version v0.2.1-824-g5566f3000
- Plugin version 3daab3749c2954df94a7c63cf71f78ec2d37b46d
- Deoplete version ac4e8b56115f1bdcda5401ea7eeb1b5a3046ebe3
- PHP language server version https://github.com/felixfbecker/php-language-server/commit/a4739430f82063ac0a1800a12bbe94d01fb1128f
- Minimal vimrc
```
let g:LanguageClient_autoStart = 1
  let g:LanguageClient_serverCommands = {
      \ 'javascript': ['javascript-typescript-stdio'],
      \ 'php': ['/usr/bin/php7.0', '/var/www/git/php/vendor/felixfbecker/language-server/bin/php-language-server.php'],
      \ 'python': ['pyls'],
      \ }
```

- Content of `:CheckHealth`. https://gist.github.com/epeli/894d295687a0563399e7abcd305b32e6
- Content of `~/.local/share/nvim/rplugin.vim`. https://gist.github.com/epeli/d8fe8f66830ca99951d3450b9d07232f

**Comment by autozimu** [comment]
Thanks for reporting.

**Comment by epeli** [comment]
I still seem to get the same error

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 52, in completion_begin
[deoplete]     self.gather_results(context), context['input'])
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 165, in merge_results
[deoplete]     result['context'])
[deoplete]   File "/var/www/git/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 86, in gather_candidates
[deoplete]     for item in items]
[deoplete]   File "/var/www/git/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 86, in <listcomp>
[deoplete]     for item in items]
[deoplete]   File "/var/www/git/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 50, in convertToDeopleteCandidate
[deoplete]     word = (item.get("textEdit", {}).get("newText") or
[deoplete] AttributeError: 'NoneType' object has no attribute 'get'
[deoplete] Error while gathering completions.  Use :messages for error details.
```

There's probably something like this going on: `{"textEdit": None}.get("textEdit", {}).get("textEdit")`

I fixed it locally and then I got this in deoplete:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 208, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/converter_truncate_menu.py", line 28, in filter
[deoplete]     max_width, '..', footer_width)
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 192, in truncate_skipping
[deoplete]     if len(string) <= max_width/2:
[deoplete] TypeError: object of type 'NoneType' has no len()
[deoplete] Could not filter using: <deoplete.filter.converter_truncate_menu.Filter object at 0x7f6503bdb518>.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 52, in completion_begin
[deoplete]     self.gather_results(context), context['input'])
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 252, in merge_results
[deoplete]     candidate.get('menu', '').find(mark) != 0):
[deoplete] AttributeError: 'NoneType' object has no attribute 'find'
[deoplete] Error while gathering completions.  Use :messages for error details
```

and 

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 208, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/converter_truncate_menu.py", line 28, in filter
[deoplete]     max_width, '..', footer_width)
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 192, in truncate_skipping
[deoplete]     if len(string) <= max_width/2:
[deoplete] TypeError: object of type 'NoneType' has no len()
[deoplete] Could not filter using: <deoplete.filter.converter_truncate_menu.Filter object at 0x7f1a73630518>.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 52, in completion_begin
[deoplete]     self.gather_results(context), context['input'])
[deoplete]   File "/var/www/git/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 253, in merge_results
[deoplete]     candidate['menu'] = mark + candidate.get('menu', '')
[deoplete] TypeError: Can't convert 'NoneType' object to str implicitly
[deoplete] Error while gathering completions.  Use :messages for error details.
```

Here's how I fixed these locally https://github.com/epeli/vimconfig/commit/b1a28ea6a458811c48730725acc78ee23bb2c3e1

But I don't think that's the way to solve this. The None is probably introduced somewhere earlier in the chain which should be fixed instead of these.

**Comment by autozimu** [comment]
Sorry about that. Please try again latest changes.

**Comment by epeli** [comment]
Seems good! Thanks!
