### ISSUE TITLE
TypeError in gather_args

### ISSUE THREAD

**Issue by sanga** [autozimu/LanguageClient-neovim#155]
Happens more or less continuously whilst in neovim. Probably happened due to updating neovim from master this morning.

```
error caught in async handler '/home/tsampson/.local/share/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient:autocmd:CursorMoved:* [['nofile',
 4]]'
Traceback (most recent call last):
  File "/home/tsampson/.local/share/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient/LanguageClient.py", line 1104, in handle_CursorMoved
    buftype, line = gather_args(["buftype", "line"], args=args)
  File "/home/tsampson/.local/share/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient/LanguageClient.py", line 70, in gather_args
    if len(args) > 1 and len(args[1]) > 0:  # from vimscript side
TypeError: object of type 'int' has no len()

```

- neovim version neovim-0.2.0ubuntu1+git201710250048+3699+26
- Plugin version (git SHA) dec2f87
- Content of `:CheckHealth`. (tricky to get this as currently neovim is basically unusable. I didn't notice any errors at least)
- Content of `~/.local/share/nvim/rplugin.vim`.

```
" python3 plugins
call remote#host#RegisterPlugin('python3', '/home/tsampson/.local/share/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient', [
      \ {'sync': v:true, 'name': 'LanguageClient_alive', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_call', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_completionItem/resolve', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_completionManager_refresh', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_exit', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentCodeAction', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentDocumentSymbol', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentReferences', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkWorkspaceSymbol', 'opts': {}, 'type': 'function'},
      \ {'sync': v:true, 'name': 'LanguageClient_getState', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'BufReadPost', 'opts': {'pattern': '*', 'eval': '{''languageId'': &filetype, ''filename'': expand(''%:p'')}'}, 'type': 'autocmd'},
      \ {'sync': v:false, 'name': 'BufWritePost', 'opts': {'pattern': '*', 'eval': '{''languageId'': &filetype, ''filename'': expand(''%:p'')}'}, 'type': 'autocmd'},
      \ {'sync': v:false, 'name': 'CursorMoved', 'opts': {'pattern': '*', 'eval': '[&buftype, line(''.'')]'}, 'type': 'autocmd'},
      \ {'sync': v:false, 'name': 'TextChanged', 'opts': {'pattern': '*', 'eval': '{''filename'': expand(''%:p''), ''buftype'': &buftype}'}, 'type': 'autocmd'},
      \ {'sync': v:false, 'name': 'TextChangedI', 'opts': {'pattern': '*', 'eval': '{''filename'': expand(''%:p''), ''buftype'': &buftype}'}, 'type': 'autocmd'},
      \ {'sync': v:false, 'name': 'LanguageClient_initialize', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_notify', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_registerServerCommands', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_rustDocument_implementations', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_setLoggingLevel', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClientStart', 'opts': {'nargs': '*', 'range': ''}, 'type': 'command'},
      \ {'sync': v:false, 'name': 'LanguageClientStop', 'opts': {}, 'type': 'command'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_codeAction', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_completion', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_completionOmnifunc', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_definition', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_didClose', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_documentSymbol', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_formatting', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_hover', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_rangeFormatting', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_references', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_rename', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_signatureHelp', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_workspace_executeCommand', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_workspace_symbol', 'opts': {}, 'type': 'function'},
     \ ])
call remote#host#RegisterPlugin('python3', '/home/tsampson/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete', [
      \ {'sync': v:false, 'name': '_deoplete_init', 'opts': {}, 'type': 'function'},
     \ ])


" ruby plugins


" python plugins



```

**Comment by sanga** [comment]
UpdateRemotePlugins fixed this actually. I was under the impression that running PlugUpdate would run updateremotePlugins but apparently I was mistaken. Anyway, my bad. Apologies for the noise.
