### ISSUE TITLE
Windows: Failed to start language server error when calling LanguageClient_textDocument_definition

### ISSUE THREAD

**Issue by sp0ng3w0rthy** [autozimu/LanguageClient-neovim#156]
**Version**: `NVIM v0.2.1-1124-g59bdc7a65`
**Plugin version (commit hash)**: `66a8b3b2fba2982f1b57a44aa53a00b57d2d54e5`
**Minimal test `_vimrc`**:
```
"""""""""""""""""""""""""
"  Plug Plugin Manager  "
"""""""""""""""""""""""""
call plug#begin('~/vimfiles/plugged')
Plug 'PProvost/vim-ps1'
Plug 'joonty/vdebug'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' }
Plug 'roxma/LanguageServer-php-neovim',  {'do': 'composer install && composer run-script parse-stubs'}
call plug#end()

"""""""""""""""""""""""""
"       Variables       "
"""""""""""""""""""""""""
let g:python3_host_prog = 'C:\dev\Python35\python.exe'
let g:deoplete#enable_at_startup = 1
let g:LanguageClient_autoStart = 1
let g:LanguageClient_serverCommands = {
    \ 'php': ['php','~\vimfiles\plugged\LanguageServer-php-neovim\vendor\felixfbecker\language-server\bin\php-language-server.php'],
    \ }
```
CheckHealth:
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - WARNING: "deoplete.nvim" is not registered.
  - WARNING: Out of date
    - ADVICE:
      - Run `:UpdateRemotePlugins`

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - INFO: Disabled. g:loaded_python_provider=1

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "C:\dev\Python35\python.exe"
  - INFO: Executable: C:\dev\Python35\python.exe
  - INFO: Python3 version: 3.5.4
  - INFO: python.exe-neovim version: 0.1.13
  - OK: Latest python.exe-neovim is installed: 0.1.13

## Ruby provider (optional)
...
```
rplugin.vim:
```
" python3 plugins
call remote#host#RegisterPlugin('python3', 'C:/Users/gvw/vimfiles/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient', [
      \ {'sync': v:true, 'name': 'LanguageClient_alive', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_call', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_completionItem/resolve', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_completionManager_refresh', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_exit', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentCodeAction', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentDocumentSymbol', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentReferences', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkWorkspaceSymbol', 'opts': {}, 'type': 'function'},
      \ {'sync': v:true, 'name': 'LanguageClient_getState', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'BufReadPost', 'opts': {'pattern': '*', 'eval': '[{''languageId'': &filetype, ''filename'': expand(''%:p'')}]'}, 'type': 'autocmd'},
      \ {'sync': v:false, 'name': 'BufWritePost', 'opts': {'pattern': '*', 'eval': '[{''languageId'': &filetype, ''filename'': expand(''%:p'')}]'}, 'type': 'autocmd'},
      \ {'sync': v:false, 'name': 'CursorMoved', 'opts': {'pattern': '*', 'eval': '[{''buftype'': &buftype, ''line'': line(''.'')}]'}, 'type': 'autocmd'},
      \ {'sync': v:false, 'name': 'TextChanged', 'opts': {'pattern': '*', 'eval': '[{''filename'': expand(''%:p''), ''buftype'': &buftype}]'}, 'type': 'autocmd'},
      \ {'sync': v:false, 'name': 'TextChangedI', 'opts': {'pattern': '*', 'eval': '[{''filename'': expand(''%:p''), ''buftype'': &buftype}]'}, 'type': 'autocmd'},
      \ {'sync': v:false, 'name': 'LanguageClient_initialize', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_notify', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_registerServerCommands', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_rustDocument_implementations', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_setLoggingLevel', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClientStart', 'opts': {'nargs': '*', 'range': ''}, 'type': 'command'},
      \ {'sync': v:false, 'name': 'LanguageClientStop', 'opts': {}, 'type': 'command'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_codeAction', 'opts': {}, 'type': 'function'},
      \ {'sync': v:true, 'name': 'LanguageClient_textDocument_completion', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_completionOmnifunc', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_definition', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'textDocument_didChange', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_didClose', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'textDocument_didSave', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_documentSymbol', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_formatting', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_hover', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_rangeFormatting', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_references', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_rename', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_signatureHelp', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_workspace_executeCommand', 'opts': {}, 'type': 'function'},
      \ {'sync': v:false, 'name': 'LanguageClient_workspace_symbol', 'opts': {}, 'type': 'function'},
     \ ])
call remote#host#RegisterPlugin('python3', 'C:/Users/gvw/vimfiles/plugged/deoplete.nvim/rplugin/python3/deoplete', [
      \ {'sync': v:false, 'name': '_deoplete_init', 'opts': {}, 'type': 'function'},
     \ ])

" ruby plugins

" python plugins
```
### Reproduction Steps
- Run `nvim index.php`
- Attempt <c-x><c-o> completion on standard php functions succeeds:

![capture](https://user-images.githubusercontent.com/10582405/32323636-5f38fe6c-bfd1-11e7-9584-001c1890feee.PNG)

- Run `:call LanguageClient_textDocument_definition()` returns the `Failed to start language server`
error, see following logs:

LanguageClient.log:
```
13:17:21 WARNING [MainThread] Unknown parameter key: rootPath
13:17:21 ERROR   [RPC-php   ] Error deserializing server output: 
Traceback (most recent call last):
  File "C:/Users/gvw/vimfiles/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\RPC.py", line 72, in serve
    msg = json.loads(content)
  File "C:\dev\Python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\dev\Python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\dev\Python35\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
LanguageServer.log:
```
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in C:\Users\gvw\vimfiles\plugged\LanguageServer-php-neovim\vendor\felixfbecker\language-server\src\Index\ReadableIndex.php on line 1
```

Any help would be greatly appreciated.

**Comment by DeltaEvo** [comment]
This issue is not from LanguageClient-neovim, it's from php-language-server
it seems to be a memory allocation issue
```
Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in 
```
PS: Memory usage seems to be a known issue of php-language-server
https://github.com/felixfbecker/php-language-server/issues?utf8=%E2%9C%93&q=memory

**Comment by sp0ng3w0rthy** [comment]
I see, thanks for the info @DeltaEvo, I've decided to simply run the server as a different process (either locally or in a Docker container perhaps) and simply connect to it using `php-language-server`'s `--tcp-server=host:port` option, we'll see how it goes.

**Comment by autozimu** [comment]
This plugin does not support connecting language servers through tcp yet. (TODO)

The other point is that, running tcp mode won't make any difference in this case as currently with stdio mode, the language server is running in separate process. I'm not familiar with php, maybe there are some parameters to control maximum size of memory consumed by php VM.

Also the error message is misleading, will fix it later.

**Comment by autozimu** [comment]
Closing this as it is not issue of this repo.

**Comment by sp0ng3w0rthy** [comment]
For anyone interested, Instead of using Windows' STDIN/STDOUT I've decided to go with [this suggestion] (https://github.com/felixfbecker/php-language-server#--tcp-serverhostport-optional) written in `php-language-server`'s README.
In order to run this in a more constant manner, I put this project in a Docker container and added the  `php bin/php-language-server.php --tcp-server=127.0.0.1:12345` command to the container's CMD.
