### ISSUE TITLE
Errors are not shown

### ISSUE THREAD

**Issue by alexcastano** [autozimu/LanguageClient-neovim#170]
I have the plugin working with https://github.com/JakeBecker/elixir-ls#features

The development of this language server for elixir is still very primitive but it has some functionalities working. The formatter and autocompletion currently work, however, the "Inline reporting of build warnings and errors" seems work but they are not shown in nvim.

```
/tmp/LanguageClient.log
16:41:26 DEBUG   [MainThread] state.file:///home/alex/jalar.ex.line_diagnostics: {26: '[Error] ** (TokenMissingError) jalar.ex:27: missing terminator: end (for "do" starting at line 1)\n    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6\n'} => {26: '[Error] ** (TokenMissingError) jalar.ex:27: missing terminator: end (for "do" starting at line 1)\n    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6\n'}
```
So it receives the errors, but then they are not shown. What can I do? Do I need another plugin?

```
" init.vim
call plug#begin('~/.vim/plugged')

Plug 'AndrewRadev/splitjoin.vim'
Plug 'KabbAmine/zeavim.vim'
Plug 'SirVer/ultisnips'
Plug 'airblade/vim-gitgutter'
Plug 'altercation/vim-colors-solarized'
Plug 'andyl/vim-projectionist-elixir'
Plug 'benmills/vimux'
Plug 'chrisbra/csv.vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'danro/rename.vim'
Plug 'godlygeek/tabular'
Plug 'janko-m/vim-test'
Plug 'kana/vim-textobj-entire'
Plug 'kana/vim-textobj-user'
Plug 'kchmck/vim-coffee-script'
Plug 'majutsushi/tagbar'
Plug 'mileszs/ack.vim'
Plug 'moll/vim-bbye'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'nelstrom/vim-visual-star-search'
Plug 'neomake/neomake'
Plug 'nicwest/QQ.vim'
Plug 'pbrisbin/vim-mkdir'
Plug 'plasticboy/vim-markdown'
Plug 'powerman/vim-plugin-AnsiEsc'
Plug 'sheerun/vim-polyglot'
" Plug 'slashmili/alchemist.vim'
Plug 'szw/vim-maximizer'
Plug 'tmux-plugins/vim-tmux'
Plug 'tommcdo/vim-exchange'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-rake'
Plug 'tpope/vim-rbenv'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rsi'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'wesQ3/vim-windowswap'

if has('nvim')
  Plug 'autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' }
  Plug 'roxma/nvim-completion-manager'
  Plug 'Shougo/echodoc.vim'

  let g:LanguageClient_serverCommands = {
        \ 'elixir': ['/home/alex/bin/elixirls'],
        \ }
  let g:LanguageClient_autoStart = 1
  let g:LanguageClient_diagnosticsEnable = 1
endif

call plug#end()
```

**Comment by autozimu** [comment]
Can you simplify vimrc?

**Comment by alexcastano** [comment]
I found the problem! The compiler locates the problem in the line 26. The file has 25 lines. I opened a `do` without an `end`:

```elixir
defmodule Test
  def hello(test) do
  ...
  ...
end # only one end
``` 

If I add a new line at the end, it is shown. So I don't know where I should report the bug, here or should I go to elixir lang? Maybe other languages server do the same... or maybe not.

Thank you for your time

**Comment by autozimu** [comment]
It should go to language server, in your case, elixir language server.

**Comment by autozimu** [comment]
As far as I know, python, rust, javascript/typescript language servers don't have this issue.
