### ISSUE TITLE
No module named 'typing'

### ISSUE THREAD

**Issue by whitebyte** [autozimu/LanguageClient-neovim#194]
Hi, I'm trying to install and launch javascript-clinet, but encounered the following error:
```
Encountered ImportError loading plugin at /home/eye1/.local/share/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient: No module named 'typing'                                                                     
Traceback (most recent call last):
  File "/home/eye1/.local/lib64/python3.4/site-packages/neovim/plugin/host.py", line 130, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib64/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
ImportError: No module named 'typing'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/eye1/.local/share/nvim/rplugin.vim
```

I'm pretty sure that `sudo pip3 install --upgrade typing` was succesful, but the error persists. 

---

Have you followed the instructions at
[INSTALL.md](https://github.com/autozimu/LanguageClient-neovim/blob/master/INSTALL.md)? - Yes

- neovim version - NVIM v0.2.3-94-gaec81f44d
- Plugin version (git SHA) - 71f103d
- Minimal vimrc = https://github.com/autozimu/LanguageClient-neovim/blob/master/min-init.vim
- Content of `:CheckHealth`.
```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    /usr/bin/python2 does not have the "neovim" module. :help provider-python
    /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
    python2.6 not found in search path or not executable.
    /usr/bin/python is Python 3.4 and cannot provide Python 2.
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help provider-python
          /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.4 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.4.5
  - INFO: python3-neovim version: 0.2.0
  - OK: Latest python3-neovim is installed: 0.2.0

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

```
- Content of `~/.local/share/nvim/rplugin.vim`.

```
" node plugins
" python3 plugins
" ruby plugins
" python plugins

```
- Language server name and version - javascript-typescript-langserver, 71f103d
- Reproduction steps (from clean state): do `UpdateRemotePlugins`

- Run `:call LanguageClient_setLoggingLevel('DEBUG')` - unknown command

**Comment by autozimu** [comment]
Make sure you are installing python module to the right python interpreter. i.e., instead of `sudo pip3 install --upgrade typing`, you can use something like
```
sudo /usr/bin/pip3 install --upgrade typing
```

**Comment by whitebyte** [comment]
Tried, still no luck

**Comment by whitebyte** [comment]
Closing. This is not an issue with Langserver, but with Gentoo's qurks of pip3
