### ISSUE TITLE
E158: Invalid buffer name

### ISSUE THREAD

**Issue by boojinks** [autozimu/LanguageClient-neovim#199]
I'm currently consistently receiving the above error when using the LanguageClient-neovim package.

Details are as follows:
Neovim: v0.2.2
Platform: Windows 7 x64
Python: 3.6.3 x64
LanguageClient-neovim: eac16849eb5cb5592cf043fa222282a7082f257b
Language server: javascript-typescript-langserver 2.5.5

:messages output
```
c:\dev\foo
10 more lines
Neoformat: no change necessary with prettier
"tsconfig.json" [New] 10L, 183C written
Neoformat: prettier formatted buffer
error caught while executing async callback:
NvimError(b'Vim(sign):E158: Invalid buffer name: C:\\dev\\foo\\src\\index.ts',)
Traceback (most recent call last):

  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\LanguageClient.py", line 1162, in textDocument_publishDiagnostics
    show_diagnostics(uri, diagnostics)

  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\LanguageClient.py", line 284, in show_diagnostics
    execute_command(cmd)

  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\state.py", line 134, in execute_command
    state["nvim"].command(command)

  File "C:\Users\REDACTED\AppData\Local\Python\Python36\site-packages\neovim\api\nvim.py", line 217, in command
    return self.request('nvim_command', string, **kwargs)

  File "C:\Users\REDACTED\AppData\Local\Python\Python36\site-packages\neovim\api\nvim.py", line 130, in request
    res = self._session.request(name, *args, **kwargs)

  File "C:\Users\REDACTED\AppData\Local\Python\Python36\site-packages\neovim\msgpack_rpc\session.py", line 97, in request
    raise self.error_wrapper(err)

neovim.api.nvim.NvimError: b'Vim(sign):E158: Invalid buffer name: C:\\dev\\foo\\src\\index.ts'
 
the call was requested at
  File "C:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\RPC.py", line 97, in serve
    self.handle(msg)
  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\RPC.py", line 110, in handle
    self.on_call(message)
  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\LanguageClient.py", line 1495, in handle_request_and_notify
    state["nvim"].async_call(getattr(self, method), message.get("params"))
error caught while executing async callback:
NvimError(b'Vim(sign):E158: Invalid buffer name: C:\\dev\\foo\\src\\index.ts',)
Traceback (most recent call last):

  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\LanguageClient.py", line 1162, in textDocument_publishDiagnostics
    show_diagnostics(uri, diagnostics)

  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\LanguageClient.py", line 284, in show_diagnostics
    execute_command(cmd)

  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\state.py", line 134, in execute_command
    state["nvim"].command(command)

  File "C:\Users\REDACTED\AppData\Local\Python\Python36\site-packages\neovim\api\nvim.py", line 217, in command
    return self.request('nvim_command', string, **kwargs)

  File "C:\Users\REDACTED\AppData\Local\Python\Python36\site-packages\neovim\api\nvim.py", line 130, in request
    res = self._session.request(name, *args, **kwargs)

  File "C:\Users\REDACTED\AppData\Local\Python\Python36\site-packages\neovim\msgpack_rpc\session.py", line 97, in request
    raise self.error_wrapper(err)

neovim.api.nvim.NvimError: b'Vim(sign):E158: Invalid buffer name: C:\\dev\\foo\\src\\index.ts'
 
the call was requested at
  File "C:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\RPC.py", line 97, in serve
    self.handle(msg)
  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\RPC.py", line 110, in handle
    self.on_call(message)
  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\LanguageClient.py", line 1495, in handle_request_and_notify
    state["nvim"].async_call(getattr(self, method), message.get("params"))
error caught while executing async callback:
NvimError(b'Vim(sign):E158: Invalid buffer name: C:\\dev\\foo\\src\\index.ts',)
Traceback (most recent call last):

  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\LanguageClient.py", line 1162, in textDocument_publishDiagnostics
    show_diagnostics(uri, diagnostics)

  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\LanguageClient.py", line 284, in show_diagnostics
    execute_command(cmd)

  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\state.py", line 134, in execute_command
    state["nvim"].command(command)

  File "C:\Users\REDACTED\AppData\Local\Python\Python36\site-packages\neovim\api\nvim.py", line 217, in command
    return self.request('nvim_command', string, **kwargs)

  File "C:\Users\REDACTED\AppData\Local\Python\Python36\site-packages\neovim\api\nvim.py", line 130, in request
    res = self._session.request(name, *args, **kwargs)

  File "C:\Users\REDACTED\AppData\Local\Python\Python36\site-packages\neovim\msgpack_rpc\session.py", line 97, in request
    raise self.error_wrapper(err)

neovim.api.nvim.NvimError: b'Vim(sign):E158: Invalid buffer name: C:\\dev\\foo\\src\\index.ts'
 
the call was requested at
  File "C:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\RPC.py", line 97, in serve
    self.handle(msg)
  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\RPC.py", line 110, in handle
    self.on_call(message)
  File "C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3\LanguageClient\LanguageClient.py", line 1495, in handle_request_and_notify
    state["nvim"].async_call(getattr(self, method), message.get("params"))
```

rplugin.vim contents
```
" node plugins


" python3 plugins
call remote#host#RegisterPlugin('python3', 'C://Users/REDACTED/AppData/Local/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient', [
      \ {'sync': v:true, 'name': 'LanguageClient_alive', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_call', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_completionItem/resolve', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_completionManager_refresh', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_exit', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentCodeAction', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentDocumentSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentReferences', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkWorkspaceSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'LanguageClient_getState', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'BufReadPost', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': '[{''buftype'': &buftype, ''languageId'': &filetype, ''filename'': expand(''%:p'')}]'}},
      \ {'sync': v:false, 'name': 'BufWritePost', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': '[{''languageId'': &filetype, ''filename'': expand(''%:p'')}]'}},
      \ {'sync': v:false, 'name': 'CursorMoved', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': '[{''buftype'': &buftype, ''line'': line(''.'')}]'}},
      \ {'sync': v:false, 'name': 'TextChanged', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': '[{''filename'': expand(''%:p''), ''buftype'': &buftype}]'}},
      \ {'sync': v:false, 'name': 'TextChangedI', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': '[{''filename'': expand(''%:p''), ''buftype'': &buftype}]'}},
      \ {'sync': v:false, 'name': 'LanguageClient_initialize', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_notify', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_registerServerCommands', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_rustDocument_implementations', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_setLoggingLevel', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClientStart', 'type': 'command', 'opts': {'nargs': '*', 'range': ''}},
      \ {'sync': v:false, 'name': 'LanguageClientStop', 'type': 'command', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_codeAction', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'LanguageClient_textDocument_completion', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_completionOmnifunc', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_definition', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'textDocument_didChange', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_didClose', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'textDocument_didSave', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_documentSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_formatting', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_hover', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_rangeFormatting', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_references', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_rename', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_signatureHelp', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_workspace_didChangeConfiguration', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_workspace_executeCommand', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_workspace_symbol', 'type': 'function', 'opts': {}},
     \ ])


" ruby plugins


" python plugins


```

/tmp/LanguageServer.log
```
```

[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/1542688/LanguageClient.log)

In order to produce the bug, I created the following typescript file:

index.ts
```
interface foo {
  id: number;
  description: string;
}
```

and began typing the word 'foo'.

I imagine it is during the generation of auto-completion candidates that the error is occurring but I'm at a loss as to where to go from here.

Any help would be much appreciated.

**Comment by boojinks** [comment]
Looking through and it appears that the error is probably caused by this response from the language server...

```
12:54:50 INFO    [MainThread] completionManager_refresh: [{'scopes': ['typescript'], 'cm_refresh_patterns': ['\\.'], 'cm_refresh': 'LanguageClient_completionManager_refresh', 'early_cache': 0, 'name': 'LanguageClient_typescript', 'priority': 9, 'enable': 1, 'auto_popup': 1, 'sort': 1, 'abbreviation': '', 'cm_refresh_length': 3}, {'scope_match': 'typescript', 'lnum': 6, 'bufnr': 2, 'changedtick': 196, 'typed': 'foo', 'base': 'foo', 'filetype': 'typescript', 'curpos': [0, 6, 4, 0, 4], 'col': 4, 'early_cache': False, 'filepath': 'c:\\dev\\foo\\src\\index.ts', 'scope': 'typescript', 'force': 0, 'startcol': 1, 'match_end': 0}]
```

The language server in question is returning the Windows path to the file which I assume is then used as a buffer name somewhere along the way (which is causing the error, as the buffer in Neovim is called "c:\dev\foo\src\index.ts" without the extra slashes.

**Comment by boojinks** [comment]
I think I have tracked the issue down to the following code

When the diagnostics are returned from the language server, [show_diagnostics](https://github.com/autozimu/LanguageClient-neovim/blob/eac16849eb5cb5592cf043fa222282a7082f257b/rplugin/python3/LanguageClient/LanguageClient.py#L247) calls
[uri_to_path](https://github.com/autozimu/LanguageClient-neovim/blob/eac16849eb5cb5592cf043fa222282a7082f257b/rplugin/python3/LanguageClient/util.py#L108-L109) which returns
`C:\\dev\\foo\\src\\index.ts` 
as the path, which is then presumably utilised as a buffer name in [here](https://github.com/autozimu/LanguageClient-neovim/blob/eac16849eb5cb5592cf043fa222282a7082f257b/rplugin/python3/LanguageClient/util.py#L130-L162).

I'll see if I can come up with a fix for this and make sure that this is what is causing the issue.

**Comment by boojinks** [comment]
As an update, it turns out that the path is being correctly converted back to its single slash version.

The issue is caused when the sign commands are actually executed - there is a casing difference between the buffer name in LanguageClient-neovim and the actual buffer name neovim is using which then causes the invalid buffer name error.

In this instance, the drive letter is lower-case in neovim but uppercase in the language client. 

I'm not 100% sure how to proceed from here but will continue working on it.

**Comment by autozimu** [comment]
Ideally, the fix should be done on language server side.

In the `initialize` request, the message send to server contains `"rootPath":"c:\\dev\\foo","rootUri":"file:///c:/dev/foo"`, both use small case driver letter. So ideally the server should send back uris following same convention.

Albeit it is the ideal approach, it might not easy to get it into upstream. It could also be done in client side with some overheads.  We could check both versions of path `C:\\dev` and `c:\\dev`  with vim's function `bufexists()`, and pick the one returns true.
