### ISSUE TITLE
Gracefully deactivate when binary not found

### ISSUE THREAD

**Issue by mqudsi** [autozimu/LanguageClient-neovim#230]
rust's `rls` language server is built in a very buggy fashion and [it is considered "normal" for it to be missing](https://github.com/rust-lang-nursery/rls/issues/535#issuecomment-349114716) after running `rustup update` if the nightly build of rls is broken.

The latest development builds of LanguageClient properly detect this case (`languageclient: Not executable!` is echoed to the error log) but thereafter deoplete chokes up:

```
"src/main.rs" 19L, 413C
languageclient: Not executable!
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 136, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 29, in gather_candidates
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 136, in gather_results
[deoplete] Too many errors from "LanguageClient". This source is disabled until Neovim is restarted.
[deoplete]   File "/usr/local/lib/python3.5/dist-packages/neovim/api/nvim.py", line 230, in call
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 29, in gather_candidates
[deoplete]   File "/usr/local/lib/python3.5/dist-packages/neovim/api/nvim.py", line 131, in request
[deoplete]     self.vim.funcs.LanguageClient_omniComplete()
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.5/dist-packages/neovim/api/nvim.py", line 230, in call
[deoplete]   File "/usr/local/lib/python3.5/dist-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]     raise self.error_wrapper(err)
[deoplete]   File "/usr/local/lib/python3.5/dist-packages/neovim/api/nvim.py", line 131, in request
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):E900: Invalid channel id'
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete] Errors from: LanguageClient.  Use :messages for error details.
[deoplete]   File "/usr/local/lib/python3.5/dist-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):E900: Invalid channel id'
[deoplete] Errors from: LanguageClient.  Use :messages for error details.                                                                                                                          
```

Would it be possible for LanguageClient to handle such error cases more gracefully in such a manner that deoplete does not throw a fit?

(again, this is not filed as a bug report but rather a feature defect. If a reproducible case is still required, kindly let me know and I'll be happy to oblige.)

**Comment by mqudsi** [comment]
Thank you kindly.
