### ISSUE TITLE
No autocompletion: register completion manager source failed.

### ISSUE THREAD

**Issue by bew** [autozimu/LanguageClient-neovim#324]
Neovim/vim version: `NVIM v0.2.2`
OS: Archlinux, kernel `4.15.6`

- Plugin version (git SHA): `fbc4686`
- Minimal vimrc:
```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'Shougo/deoplete.nvim',
            \ { 'do': ':UpdateRemotePlugins' }

Plug 'autozimu/LanguageClient-neovim',
            \ {
            \   'branch': 'next',
            \   'do': 'bash install.sh',
            \ }

let g:LanguageClient_serverCommands = {
    \ 'crystal': [$HOME . '/Projects/opensource/scry/bin/scry'],
    \ }

call plug#end()

let g:LanguageClient_loggingLevel = 'DEBUG'
```

- Language server name/link and version: Scry (https://github.com/crystal-lang-tools/scry), version tag `v0.7.0` (commit: `5c983db`).
 This is a language server in development (for a language in development :smiley: )
- Reproduction steps (from clean state)

1. Open a crystal file, for example:
```cr
puts "Hello world" # :)

# vim:set ft=crystal:
```

2. Start the server with: `:LanguageClientStart`

- Logs. Ensure `let g:LanguageClient_loggingLevel = 'DEBUG'` is in minimal
  vimrc. Follow previous provided reproduction steps to reproduce the bug.
  Attach contents of `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`.
  * `LanguageClient.log` is empty (it uses another file for logging), but here is the log file for scry:
```
I, [2018-03-07 16:49:36 -08:00 #17085]  INFO -- : Scry is looking into your code...
D, [2018-03-07 16:49:36 -08:00 #17085] DEBUG -- : Content-Length: 327
D, [2018-03-07 16:49:36 -08:00 #17085] DEBUG -- : 
D, [2018-03-07 16:49:36 -08:00 #17085] DEBUG -- : {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":17084,"rootPath":"/home/lesell_b/.config/nvim","rootUri":"file:///home/lesell_b/.config/nvim","initializationOptions":null,"capabilities":{"workspace":{"applyEdit":true},"textDocument":{"completion":{"completionItem":{"snippetSupport":true}}}},"trace":"off"}}
D, [2018-03-07 16:49:36 -08:00 #17085] DEBUG -- : initialize
D, [2018-03-07 16:49:36 -08:00 #17085] DEBUG -- : Starting to build dependancy graph for these paths: /home/lesell_b/.config/nvim/lib
lib
/usr/lib/crystal
/home/lesell_b/.config/nvim
D, [2018-03-07 16:49:37 -08:00 #17085] DEBUG -- : Finished building the dependancy graph got these nodes: <veeeerrryyyy looong line>
D, [2018-03-07 16:49:37 -08:00 #17085] DEBUG -- : Content SEND: Content-Length: 244

{"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":1,"documentFormattingProvider":true,"definitionProvider":true,"documentSymbolProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".","\"","/"]}}}}
D, [2018-03-07 16:49:37 -08:00 #17085] DEBUG -- : Content-Length: 86
D, [2018-03-07 16:49:37 -08:00 #17085] DEBUG -- : 
D, [2018-03-07 16:49:37 -08:00 #17085] DEBUG -- : {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{}}}
D, [2018-03-07 16:49:37 -08:00 #17085] DEBUG -- : Content SEND: Content-Length: 833

{"jsonrpc":"2.0","error":{"code":-32001,"message":"Couldn't parse (Scry::NotificationMessage | Scry::RequestMessage) from {\"jsonrpc\":\"2.0\",\"method\":\"workspace/didChangeConfiguration\",\"params\":{\"settings\":{}}} at 1:1","data":["/usr/lib/crystal/json/from_json.cr:230:3 in 'new'","/usr/lib/crystal/json/from_json.cr:13:3 in 'from_json'","/home/lesell_b/Projects/opensource/scry/src/scry/message.cr:19:7 in 'parse'","/home/lesell_b/Projects/opensource/scry/src/scry.cr:22:19 in 'start'","/home/lesell_b/Projects/opensource/scry/src/scry.cr:40:1 in '__crystal_main'","/usr/lib/crystal/crystal/main.cr:11:3 in '_crystal_main'","/usr/lib/crystal/crystal/main.cr:112:5 in 'main_user_code'","/usr/lib/crystal/crystal/main.cr:101:7 in 'main'","/usr/lib/crystal/crystal/main.cr:135:3 in 'main'","__libc_start_main","_start","???"]}}
D, [2018-03-07 16:49:37 -08:00 #17085] DEBUG -- : Content-Length: 225
D, [2018-03-07 16:49:37 -08:00 #17085] DEBUG -- : 
D, [2018-03-07 16:49:37 -08:00 #17085] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","languageId":"crystal","version":1,"text":"puts \"hello world\" # :)\n\n# vim:set ft=crystal:\n"}}}
D, [2018-03-07 16:49:37 -08:00 #17085] DEBUG -- : textDocument/didOpen
D, [2018-03-07 16:49:37 -08:00 #17085] DEBUG -- : Content SEND: Content-Length: 139

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[]}}
```
  * `LanguageServer.log`:
```
16:49:36 WARNING [MainThread] Unknown parameter key: rootPath
16:49:36 WARNING [MainThread] Unknown parameter key: settingsPath
16:49:37 WARNING [MainThread] register completion manager source failed. Error: NvimError(b'Error calling function.',)
16:49:37 ERROR   [RPC-crystal] Error handling message: {"jsonrpc":"2.0","error":{"code":-32001,"message":"Couldn't parse (Scry::NotificationMessage | Scry::RequestMessage) from {\"jsonrpc\":\"2.0\",\"method\":\"workspace/didChangeConfiguration\",\"params\":{\"settings\":{}}} at 1:1","data":["/usr/lib/crystal/json/from_json.cr:230:3 in 'new'","/usr/lib/crystal/json/from_json.cr:13:3 in 'from_json'","/home/lesell_b/Projects/opensource/scry/src/scry/message.cr:19:7 in 'parse'","/home/lesell_b/Projects/opensource/scry/src/scry.cr:22:19 in 'start'","/home/lesell_b/Projects/opensource/scry/src/scry.cr:40:1 in '__crystal_main'","/usr/lib/crystal/crystal/main.cr:11:3 in '_crystal_main'","/usr/lib/crystal/crystal/main.cr:112:5 in 'main_user_code'","/usr/lib/crystal/crystal/main.cr:101:7 in 'main'","/usr/lib/crystal/crystal/main.cr:135:3 in 'main'","__libc_start_main","_start","???"]}}
Traceback (most recent call last):
  File "/home/lesell_b/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient/RPC.py", line 97, in serve
    self.handle(msg)
  File "/home/lesell_b/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient/RPC.py", line 106, in handle
    mid = message["id"]
KeyError: 'id'
```

The last error (the ERROR line with the KeyError python exception) is because Scry doesn't handle `workspace/didChangeConfiguration`, raises an exception and send a response to the LS client without an `id` in the response, this is a known issue https://github.com/crystal-lang-tools/scry/issues/52, and I don't think it has anything to do with this autocompletion issue here.

Ask if you need more data!

**Comment by autozimu** [comment]
It looks like you are using the legacy python implementation, which is no longer actively maintained.

Please remove your current plugin installation and try it again.

**Comment by bew** [comment]
Oh right, it was an old installation that got activated when I re-enabled the plugin in Plug. After full reinstall I don't have those errors anymore.

But now I still don't have auto completion: The server gets quite a lot of `textDocument/publishDiagnostics` requests, but never a completion request, even though it tells the client that it handles completion.

Here is the json with capabilities & trigger characters:
```json
{
  "jsonrpc": "2.0",
  "id": 11,
  "result": {
    "capabilities": {
      "textDocumentSync": 1,
      "documentFormattingProvider": true,
      "definitionProvider": true,
      "documentSymbolProvider": true,
      "completionProvider": {
        "resolveProvider": true,
        "triggerCharacters": [ ".", "\"", "/" ]
      }
    }
  }
}
```
The full scry logs:
```
I, [2018-03-07 17:22:53 -08:00 #23275]  INFO -- : Scry is looking into your code...
D, [2018-03-07 17:22:53 -08:00 #23275] DEBUG -- : Content-Length: 383
D, [2018-03-07 17:22:53 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:22:53 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"completion":{"completionItem":{"commitCharactersSupport":null,"documentationFormat":null,"snippetSupport":false},"dynamicRegistration":null}}},"initializationOptions":null,"processId":23154,"rootPath":"/home/lesell_b/.config/nvim","rootUri":"file:///home/lesell_b/.config/nvim","trace":"off"},"id":11}
D, [2018-03-07 17:22:53 -08:00 #23275] DEBUG -- : initialize
D, [2018-03-07 17:22:53 -08:00 #23275] DEBUG -- : Starting to build dependancy graph for these paths: /home/lesell_b/.config/nvim/lib
lib
/usr/lib/crystal
/home/lesell_b/.config/nvim
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : Finished building the dependancy graph got these nodes: <very long line>
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 245

{"jsonrpc":"2.0","id":11,"result":{"capabilities":{"textDocumentSync":1,"documentFormattingProvider":true,"definitionProvider":true,"documentSymbolProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".","\"","/"]}}}}
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : Content-Length: 244
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"crystal","text":"puts \"hello world\" # :)\nio = IO::Memory.new\n\n# vim:set ft=crystal:","uri":"file:///home/lesell_b/.config/nvim/test.cr","version":0}}}
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : textDocument/didOpen
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 139

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[]}}
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : Content-Length: 278
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\n\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":1}}}
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:22:54 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 139

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[]}}
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : Content-Length: 279
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\ni\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":2}}}
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 139

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[]}}
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : Content-Length: 280
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nio\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":3}}}
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 139

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[]}}
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : Content-Length: 281
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nio.\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":4}}}
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:22:55 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 414

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":1}},"severity":1,"source":"Scry [Crystal]","message":"expecting any of these tokens: IDENT, CONST, +, -, *, /, %, |, &, ^, **, <<, <, <=, ==, !=, =~, !~, >>, >, >=, <=>, ===, [], []=, []?, [ (not 'EOF')"}]}}
D, [2018-03-07 17:25:32 -08:00 #23275] DEBUG -- : Content-Length: 280
D, [2018-03-07 17:25:32 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:25:32 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nio\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":5}}}
D, [2018-03-07 17:25:32 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:25:32 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 139

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[]}}
D, [2018-03-07 17:25:32 -08:00 #23275] DEBUG -- : Content-Length: 281
D, [2018-03-07 17:25:32 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:25:32 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nios\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":6}}}
D, [2018-03-07 17:25:32 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:25:32 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 139

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[]}}
D, [2018-03-07 17:25:33 -08:00 #23275] DEBUG -- : Content-Length: 280
D, [2018-03-07 17:25:33 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:25:33 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nio\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":7}}}
D, [2018-03-07 17:25:33 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:25:33 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 139

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[]}}
D, [2018-03-07 17:25:34 -08:00 #23275] DEBUG -- : Content-Length: 281
D, [2018-03-07 17:25:34 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:25:34 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nio.\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":8}}}
D, [2018-03-07 17:25:34 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:25:34 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 414

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":1}},"severity":1,"source":"Scry [Crystal]","message":"expecting any of these tokens: IDENT, CONST, +, -, *, /, %, |, &, ^, **, <<, <, <=, ==, !=, =~, !~, >>, >, >=, <=>, ===, [], []=, []?, [ (not 'EOF')"}]}}
D, [2018-03-07 17:25:36 -08:00 #23275] DEBUG -- : Content-Length: 280
D, [2018-03-07 17:25:36 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:25:36 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nio\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":9}}}
D, [2018-03-07 17:25:36 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:25:36 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 139

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[]}}
D, [2018-03-07 17:25:38 -08:00 #23275] DEBUG -- : Content-Length: 282
D, [2018-03-07 17:25:38 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:25:38 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nio.\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":10}}}
D, [2018-03-07 17:25:38 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:25:38 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 414

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":1}},"severity":1,"source":"Scry [Crystal]","message":"expecting any of these tokens: IDENT, CONST, +, -, *, /, %, |, &, ^, **, <<, <, <=, ==, !=, =~, !~, >>, >, >=, <=>, ===, [], []=, []?, [ (not 'EOF')"}]}}
D, [2018-03-07 17:25:38 -08:00 #23275] DEBUG -- : Content-Length: 283
D, [2018-03-07 17:25:38 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:25:38 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nio..\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":11}}}
D, [2018-03-07 17:25:38 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:25:38 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 287

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":1}},"severity":1,"source":"Scry [Crystal]","message":"unexpected token: EOF"}]}}
D, [2018-03-07 17:25:39 -08:00 #23275] DEBUG -- : Content-Length: 282
D, [2018-03-07 17:25:39 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:25:39 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nio.\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":12}}}
D, [2018-03-07 17:25:39 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:25:39 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 414

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":1}},"severity":1,"source":"Scry [Crystal]","message":"expecting any of these tokens: IDENT, CONST, +, -, *, /, %, |, &, ^, **, <<, <, <=, ==, !=, =~, !~, >>, >, >=, <=>, ===, [], []=, []?, [ (not 'EOF')"}]}}
D, [2018-03-07 17:25:39 -08:00 #23275] DEBUG -- : Content-Length: 281
D, [2018-03-07 17:25:39 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:25:39 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nio\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":13}}}
D, [2018-03-07 17:25:39 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:25:39 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 139

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[]}}
D, [2018-03-07 17:25:41 -08:00 #23275] DEBUG -- : Content-Length: 282
D, [2018-03-07 17:25:41 -08:00 #23275] DEBUG -- : 
D, [2018-03-07 17:25:41 -08:00 #23275] DEBUG -- : {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":null,"rangeLength":null,"text":"puts \"hello world\" # :)\nio = IO::Memory.new\nio.\n\n# vim:set ft=crystal:"}],"textDocument":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","version":14}}}
D, [2018-03-07 17:25:41 -08:00 #23275] DEBUG -- : textDocument/didChange
D, [2018-03-07 17:25:41 -08:00 #23275] DEBUG -- : Content SEND: Content-Length: 414

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/lesell_b/.config/nvim/test.cr","diagnostics":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":1}},"severity":1,"source":"Scry [Crystal]","message":"expecting any of these tokens: IDENT, CONST, +, -, *, /, %, |, &, ^, **, <<, <, <=, ==, !=, =~, !~, >>, >, >=, <=>, ===, [], []=, []?, [ (not 'EOF')"}]}}
```
I tried multiple times to add a dot `.` after an object to get completion, but it seems that the server never got a completion request...

**Comment by bew** [comment]
It looks like this is simply because you don't support `deoplete` anymore with the rewrite you did in Rust, right?
Will you re-add support for it? If no, you should remove mention to deoplete in the README I think.

**Comment by autozimu** [comment]
No. The newer rust implementation supports deoplete.

**Comment by autozimu** [comment]
Follow troubleshooting steps in INSTALL.md if you cannot get it work.

**Comment by bew** [comment]
I use nvim-completion-manager now (it's awesome!!!)

Thank you for your support :smiley:
