### ISSUE TITLE
Support for servers that connect to client-opened socket

### ISSUE THREAD

**Issue by fenuks** [autozimu/LanguageClient-neovim#413]
Some servers, [sonarlint for VSCode](https://github.com/SonarSource/sonarlint-vscode/blob/abca0dedfe6afc1a5e235963288ecfb9019344c0/src/extension.ts#L46) for instance, connect to TCP socket opened by client. Sadly, in case of sonarlint language server it's the only supported option for interaction with server.

**Comment by autozimu** [comment]
With a brief scan, I don't think that's the case. That language server will open a port and listen on it
https://github.com/SonarSource/sonarlint-vscode/blob/abca0dedfe6afc1a5e235963288ecfb9019344c0/src/extension.ts#L55

With which, this plugin already supports connecting to.

**Comment by fenuks** [comment]
I think it's the case. Client creates socket and server connects to it. 
netstat shows that VSCode linstens on the port

`tcp6       0      0 :::41579                :::*                    LISTEN      1669/code-oss`
and sonarlint connects to it.
```fenuks    1810  0.4  2.3 4848624 195996 ?      Sl   19:37   0:12 /usr/lib/jvm/default/bin/java -jar /home/fenuks/.vscode-oss/extensions/SonarSource.sonarlint-vscode-1.2.0/server/sonarlint-ls.jar 41579 file:///home/fenuks/.vscode-oss/extensions/SonarSource.sonarlint-vscode-1.2.0/analyzers/sonarjs.jar file:///home/fenuks/.vscode-oss/extensions/SonarSource.sonarlint-vscode-1.2.0/analyzers/sonarphp.jar file:///home/fenuks/.vscode-oss/extensions/SonarSource.sonarlint-vscode-1.2.0/analyzers/sonarpython.jar file:///home/fenuks/.vscode-oss/extensions/SonarSource.sonarlint-vscode-1.2.0/analyzers/sonarts.jar```
I'm no node expert, but I think that in linked code above, extension first starts listen on port, and in callback server is started that attaches to it.

**Comment by fenuks** [comment]
Trying to start sonarlint server on unassigned port gives an error as below.
```
LANG=en /usr/lib/jvm/default/bin/java -jar /home/fenuks/.vscode-oss/extensions/SonarSource.sonarlint-vscode-1.2.0/server/sonarlint-ls.jar 2222 file:///home/fenuks/.vscode-oss/extensions/SonarSource.sonarlint-vscode-1.2.0/analyzers/sonarjs.jar file:///home/fenuks/.vscode-oss/extensions/SonarSource.sonarlint-vscode-1.2.0/analyzers/sonarphp.jar file:///home/fenuks/.vscode-oss/extensions/SonarSource.sonarlint-vscode-1.2.0/analyzers/sonarpython.jar file:///home/fenuks/.vscode-oss/extensions/SonarSource.sonarlint-vscode-1.2.0/analyzers/sonarts.jar
20:40:20.596 [main] INFO  o.s.languageserver.ServerMain - Binding to 2222
20:40:20.616 [main] ERROR o.s.languageserver.ServerMain - Unable to connect to the client
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_172]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_172]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_172]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_172]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_172]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_172]
        at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_172]
        at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_172]
        at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_172]
        at org.sonarlint.languageserver.SonarLintLanguageServer.bySocket(SonarLintLanguageServer.java:145) ~[sonarlint-ls.jar:3.1.0.1376]
        at org.sonarlint.languageserver.ServerMain.main(ServerMain.java:58) ~[sonarlint-ls.jar:3.1.0.1376]
```

**Comment by autozimu** [comment]
Ah, I see.

Should be the case as you said.

**Comment by fenuks** [comment]
How difficult it would be to add support for this? And somewhat related question, in this scenario, I would want to have two language servers for java – sonarlint which has neat linter for java and jdt.ls for the rest of stuff. I believe it is not supported, yes?

**Comment by autozimu** [comment]
That’s correct.

Both would require some amount of work.

**Comment by fenuks** [comment]
Thank you for your kind answers. :-)) It would be nice to have, some time in future, perhaps. :)
