### ISSUE TITLE
didChangeWatchedFiles isn't sent on save

### ISSUE THREAD

**Issue by tbo** [autozimu/LanguageClient-neovim#459]
## Summary

I'm using the latest version of LanguageClient-neovim with [eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls). Some functionality of eclipse.jdt.ls isn't triggered, because `workspace/didChangeWatchedFiles` isn't sent on save. I originally thought this to be a problem of the language server and created this issue: eclipse/eclipse.jdt.ls#672

## Reproduction

Save a file

## Current Behavior

Only `textDocument/didSave` is sent on save.

## Expected Behavior

Both `textDocument/didSave` and `workspace/didChangeWatchedFiles` are sent to the language server on save.

**Comment by autozimu** [comment]
Please provide log files content.

**Comment by tbo** [comment]
LanguageClient.log
```
#######
LanguageClient 0.1.87 5015aa164dc9ad96a0f5fbadaf92a888d16bc0d9
#######
12:14:08 WARN main src/languageclient.rs:1895 Failed to start language server automatically. Internal error.
```

`g:LanguageClient_setLoggingLevel` is set to 'DEBUG'

Despite the error message the language server seems to work.

**Comment by autozimu** [comment]
I don't think the logging level is properly applied.

You will need either set the variable `g:LanguageClient_loggingLevel` to `"DEBUG"`, or call the function `:call LanguageClient_setLoggingLevel('DEBUG')`.

Closing this until a proper reproduction steps and logs are provided.

**Comment by tbo** [comment]
@autozimu I added the missing information:

**Steps to reproduce**

1. Create a java project: `mvn archetype:generate -DgroupId=example -DartifactId=example  -DarchetypeArtifactId=maven-archetype-quickstart`
2. Open `App.java`
3. Make a change
4. Save `:w!`

[LanguageClient.log](https://gist.github.com/tbo/fedb6b7ebf034ba440261fb88bc2bf47)

**Comment by autozimu** [comment]
Based on the log, the server did sent any notifications to register watched files, possibly there is some error on server side as the error indicates.

A correct message to register watched files is something like this
```
20:18:12 INFO reader-rust src/vim.rs:392 <= Some("rust") {"jsonrpc":"2.0","method":"client/registerCapability","id":1,"params":{"registrations":[{"id":"rls-watch","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"/Users/ljunf/repo/LanguageClient-neovim/tests/data/sample-rs/Cargo{.toml,.lock}"},{"globPattern":"/Users/ljunf/repo/LanguageClient-neovim/tests/data/sample-rs/target","kind":4}]}}]}}
```

**Comment by tbo** [comment]
@autozimu I compared this with the vscode implementation. eclipse.jdt.ls does send `client/registerCapability` when I open the project in vscode. I assumed, that it reports different capabilities, so I checked the `initialize` call for vsscode -> eclipse.jdt.ls. You can find the whole payload [here](https://gist.github.com/tbo/394e78f0763c9af1a402b79f760b90d6), but I think that these are the relevant bits:

```
{
    "processId": 86846,
    "rootPath": "/Users/tbo/git/example",
    "rootUri": "file:///Users/tbo/git/example",
    "capabilities": {
        "workspace": {
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
           [...]
            "configuration": true,
            "workspaceFolders": true
        },
        [...]
```

It seems, that `LanguageClient-neovim` doesn't sent the [WorkspaceClientCapabilities](https://microsoft.github.io/language-server-protocol/specification#initialize). I tried setting the capabilities via `settings.json` in the hopes, that it would work like `initializationOptions`, but it didn't work.

**Comment by autozimu** [comment]
OK. This `didChangeWatchedFiles.dynamicRegistration` should be sent by this client.

I formatted the error returned by language server, which indicates another issue in server side,
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:257)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:186)
        at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:83)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
        ... 12 more
Caused by: java.lang.NullPointerException
        at org.eclipse.jdt.ls.core.internal.preferences.ClientPreferences.isExecuteCommandDynamicRegistrationSupported(ClientPreferences.java:100)
        at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.initialize(InitHandler.java:162)
        at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:164)
        ... 17 more
```
