### ISSUE TITLE
vscode-html-languageserver-bin crashes when opening an html file

### ISSUE THREAD

**Issue by MartenBE** [autozimu/LanguageClient-neovim#494]
> If you are reporting a bug, please read following FAQ first. If you are
requesting other types of issue, please ignore.

- Did you upgrade to latest plugin version? **Yes**
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. **I've used `:PlugUpdate` to get the latest version**
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? **Yes**
```
health#LanguageClient#check
========================================================================
  - OK: binary found: /home/martijn/.config/nvim/plugged/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.92 
```
- Did you check [troubleshooting]? **Yes**

## Summary

When opening an HTML file, the html language server seems to crash and unable to function. We have posted an issue on their repository (https://github.com/vscode-langservers/vscode-html-languageserver-bin/issues/3), but they remain unresponsive. To be certain that the error lies only at their end, we also wanted to post the error here to double check what the cause could be and to find a fix.

The reported error is:
```
TypeError: Cannot read property 'getAllModesInDocument' of undefined
    at /usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:242:45
    at step (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:37:23)
    at Object.next (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:18:53)
    at /usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:8:12)
    at validateTextDocument (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:233:12)
    at Timeout._onTimeout (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:221:9)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
```

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`):
```
NVIM v0.3.0
Build type: RelWithDebInfo
Lua 5.3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/builddir/build/BUILD/neovim-0.3.0/build/config -I/builddir/build/BUILD/neovim-0.3.0/src -I/usr/include -I/builddir/build/BUILD/neovim-0.3.0/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.3.0/build/include
Compiled by mockbuild

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- This plugin version (`git rev-parse --short HEAD`): **2c19955**
- This plugin's binary version (`bin/languageclient --version`): **languageclient 0.1.92**
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim]):
```
call plug#begin('~/.config/nvim/plugged')
Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': 'bash install.sh' }
call plug#end()

set hidden
set signcolumn=yes

let g:LanguageClient_loggingFile = '/tmp/LanguageClient.log'
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_serverStderr = '/tmp/LanguageServer.log'
let g:LanguageClient_autoStart = 1
let g:LanguageClient_serverCommands = {}

if executable('html-languageserver')
    let g:LanguageClient_serverCommands.html = ['html-languageserver', '--stdio'] " npm install -g vscode-html-languageserver-bin
    autocmd FileType html nnoremap <buffer><Leader>f :call LanguageClient_textDocument_formatting()<CR>
else
    echo "LSP: html-languageserver not installed!\n"
endif
```
- Language server link and version: **vscode-html-languageserver-bin@1.4.0**
- Steps to reproduce the issue from clean state
    1. **Install the vscode-html-languageserver-bin html language server: npm install -g vscode-html-languageserver-bin**
    2. **Enable the html server for the html mode (see the minimal vim init file)**
    3. **Open an html file**
- Logs (Paste or attach log file content):

```
15:35:28 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"eval","params":["[!!get(g:, 'LanguageClient_autoStart', 1), get(g:, 'LanguageClient_serverCommands', {}), get(g:, 'LanguageClient_selectionUI', v:null), get(g:, 'LanguageClient_trace', v:null), get(g:, 'LanguageClient_settingsPath', '.vim/settings.json'), !!get(g:, 'LanguageClient_loadSettings', 1), get(g:, 'LanguageClient_rootMarkers', v:null), get(g:, 'LanguageClient_changeThrottle', v:null), get(g:, 'LanguageClient_waitOutputTimeout', v:null), !!get(g:, 'LanguageClient_diagnosticsEnable', 1), get(g:, 'LanguageClient_diagnosticsList', 'Quickfix'), get(g:, 'LanguageClient_diagnosticsDisplay', {}), get(g:, 'LanguageClient_windowLogMessageLevel', 'Warning'), get(g:, 'LanguageClient_hoverPreview', 'Auto'), get(g:, 'LanguageClient_completionPreferTextEdit', 0), has('nvim')]"],"id":4}
15:35:28 INFO reader-main src/vim.rs:386 <= None {"id": 4, "jsonrpc": "2.0", "result": [1, {"html": ["html-languageserver", "--stdio"]}, null, null, ".vim/settings.json", 1, null, null, null, 1, "Quickfix", {}, "Warning", "Auto", 0, 1]}
15:35:28 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"eval","params":["get(g:, 'loaded_fzf')"],"id":5}
15:35:28 INFO reader-main src/vim.rs:386 <= None {"id": 5, "jsonrpc": "2.0", "result": 1}
15:35:28 INFO main src/languageclient.rs:2528 End languageClient/startServer
15:35:28 INFO main src/languageclient.rs:214 Define signs
15:35:28 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"execute","params":["echo | execute 'sign define LanguageClientInformation text=ℹ texthl=ALEInfoSign' | execute 'sign define LanguageClientHint text=➤ texthl=ALEInfoSign' | execute 'sign define LanguageClientWarning text=⚠ texthl=ALEWarningSign' | execute 'sign define LanguageClientError text=✖ texthl=ALEErrorSign'"],"id":6}
15:35:28 INFO reader-main src/vim.rs:386 <= None {"id": 6, "jsonrpc": "2.0", "result": 0}
15:35:28 INFO main src/languageclient.rs:228 Define signs
15:35:28 INFO main src/languageclient.rs:646 Begin initialize
15:35:28 INFO main src/languageclient.rs:46 gather_args: [LanguageId, Filename] = [String("html"), String("/tmp/test.html")]
15:35:28 INFO main src/languageclient.rs:29 Some arguments are not available. Requesting from vim. Keys: ["rootPath", "hasSnippetSupport"]. Exps: ["v:null", "s:hasSnippetSupport()"]
15:35:28 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"eval","params":["[v:null, s:hasSnippetSupport()]"],"id":7}
15:35:28 INFO reader-main src/vim.rs:386 <= None {"id": 7, "jsonrpc": "2.0", "result": [null, 0]}
15:35:28 INFO main src/languageclient.rs:46 gather_args: [("rootPath", "v:null"), ("hasSnippetSupport", "s:hasSnippetSupport()")] = [Null, Number(0)]
15:35:28 WARN main src/utils.rs:72 Unknown project type. Fallback to use dir as project root: Ok("/tmp")
15:35:28 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"s:Echomsg","params":["LanguageClient project root: /tmp"],"id":8}
15:35:28 INFO reader-main src/vim.rs:386 <= None {"id": 8, "jsonrpc": "2.0", "result": 0}
15:35:28 INFO main src/languageclient.rs:666 Project root: /tmp
15:35:28 WARN main src/languageclient.rs:673 Failed to get initializationOptions: No such file or directory (os error 2)
15:35:28 INFO main src/vim.rs:90 => Some("html") {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"completion":{"completionItem":{"snippetSupport":false}}},"workspace":{"applyEdit":true,"didChangeWatchedFiles":{"dynamicRegistration":true}}},"initializationOptions":{},"processId":16014,"rootPath":"/tmp","rootUri":"file:///tmp","trace":"off"},"id":9}
15:35:29 INFO reader-html src/vim.rs:386 <= Some("html") {"jsonrpc":"2.0","id":9,"error":{"code":-32603,"message":"Request initialize failed with message: Cannot read property 'css' of undefined"}}
15:35:29 WARN main src/languageclient.rs:1960 Failed to start language server automatically. Request initialize failed with message: Cannot read property 'css' of undefined
15:35:29 INFO main src/languageclient.rs:1965 End languageClient/handleBufReadPost
15:35:29 INFO main src/languageclient.rs:2022 Begin languageClient/handleCursorMoved
15:35:29 INFO main src/languageclient.rs:46 gather_args: [Buftype, Filename, Line] = [String(""), String("/tmp/test.html"), Number(0)]
15:35:29 INFO main src/languageclient.rs:1970 Begin languageClient/handleTextChanged
15:35:29 INFO main src/languageclient.rs:46 gather_args: [Buftype, Filename] = [String(""), String("/tmp/test.html")]
15:35:29 INFO main src/languageclient.rs:1547 Begin textDocument/didChange
15:35:29 INFO main src/languageclient.rs:46 gather_args: [Buftype, LanguageId, Filename] = [String(""), String("html"), String("/tmp/test.html")]
15:35:29 INFO main src/languageclient.rs:1556 Not opened yet. Switching to didOpen.
15:35:29 INFO main src/languageclient.rs:1503 Begin textDocument/didOpen
15:35:29 INFO main src/languageclient.rs:29 Some arguments are not available. Requesting from vim. Keys: ["text"]. Exps: ["LSP#text()"]
15:35:29 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"eval","params":["[LSP#text()]"],"id":10}
15:35:29 INFO reader-main src/vim.rs:386 <= None {"id": 10, "jsonrpc": "2.0", "result": [[" <!DOCTYPE html>", "<html>", "<head>", "<meta charset=\"UTF-8\">", "<title>Title of the document</title>", "</head>", "", "<body>", "Content of the document......", "</body>", "", "</html> ", ""]]}
15:35:29 INFO main src/languageclient.rs:46 gather_args: [Buftype, LanguageId, Filename, Text] = [String(""), String("html"), String("/tmp/test.html"), Array([String(" <!DOCTYPE html>"), String("<html>"), String("<head>"), String("<meta charset=\"UTF-8\">"), String("<title>Title of the document</title>"), String("</head>"), String(""), String("<body>"), String("Content of the document......"), String("</body>"), String(""), String("</html> "), String("")])]
15:35:29 INFO main src/vim.rs:90 => Some("html") {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"html","text":" <!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"UTF-8\">\n<title>Title of the document</title>\n</head>\n\n<body>\nContent of the document......\n</body>\n\n</html> \n","uri":"file:///tmp/test.html","version":0}}}
15:35:29 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"execute","params":["setlocal omnifunc=LanguageClient#complete"],"id":11}
15:35:29 INFO reader-main src/vim.rs:386 <= None {"id": 11, "jsonrpc": "2.0", "result": 0}
15:35:29 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"s:ExecuteAutocmd","params":["LanguageClientBufReadPost"],"id":12}
15:35:29 INFO reader-main src/vim.rs:386 <= None {"id": 12, "jsonrpc": "2.0", "result": 0}
15:35:29 INFO main src/languageclient.rs:1542 End textDocument/didOpen
15:35:29 INFO main src/languageclient.rs:1995 End languageClient/handleTextChanged
15:35:29 INFO reader-html src/vim.rs:386 <= Some("html") {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"Error while validating file:///tmp/test.html: Cannot read property 'getAllModesInDocument' of undefined\nTypeError: Cannot read property 'getAllModesInDocument' of undefined\n    at /usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:242:45\n    at step (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:37:23)\n    at Object.next (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:18:53)\n    at /usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:12:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:8:12)\n    at validateTextDocument (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:233:12)\n    at Timeout._onTimeout (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:221:9)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)"}}
15:35:29 INFO main src/languageclient.rs:1700 Begin window/logMessage
15:35:29 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"s:Echomsg","params":["[Error] Error while validating file:///tmp/test.html: Cannot read property 'getAllModesInDocument' of undefined\nTypeError: Cannot read property 'getAllModesInDocument' of undefined\n    at /usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:242:45\n    at step (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:37:23)\n    at Object.next (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:18:53)\n    at /usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:12:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:8:12)\n    at validateTextDocument (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:233:12)\n    at Timeout._onTimeout (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:221:9)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)"],"id":13}
15:35:29 INFO reader-main src/vim.rs:386 <= None {"id": 13, "jsonrpc": "2.0", "result": 0}
15:35:29 INFO main src/languageclient.rs:1709 End window/logMessage
```

## Current Behavior
The html language server fails at start when opening an HTML file

## Expected Behavior
The html language server starts without failures when opening an HTML file

> Please understand the more detailed information provided, the sooner a issue
could be resolved. Low quality bug reports might be closed directly.)

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting
[min-init.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim

**Comment by MartenBE** [comment]
Thank you very much for solving this bug in such small time frame :+1: !

With kind regards,

Marten

**Comment by JeanMertz** [comment]
Could it be that something made this error show up again?

I'm using the latest commit of the `next` branch locally (d31e492), and seeing the same error, even when using the `sample-html/index.html` file added in 514cc4d:

```
[LC] [Error] Error while validating file:///Users/jean/Development/Projects/Contributions/LanguageClient-neovim/tests/data/sample-html/index.html: Cannot read property 'getAllModesInDocument' of undefined

TypeError: Cannot read property 'getAllModesInDocument' of undefined
    at /Users/jean/.config/nvm/11.12.0/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:242:45
    at step (/Users/jean/.config/nvm/11.12.0/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:37:23)
    at Object.next (/Users/jean/.config/nvm/11.12.0/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:18:53)
    at /Users/jean/.config/nvm/11.12.0/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jean/.config/nvm/11.12.0/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:8:12)
    at validateTextDocument (/Users/jean/.config/nvm/11.12.0/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:233:12)
    at Timeout._onTimeout (/Users/jean/.config/nvm/11.12.0/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:221:9)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
```
