### ISSUE TITLE
PHP LSP errors in SpaceVim

### ISSUE THREAD

**Issue by johnnypea** [autozimu/LanguageClient-neovim#521]
I already issued my problem here https://github.com/SpaceVim/SpaceVim/issues/1948 but it looks like it's probably a bug in LanguageClient-neovim itself.

OS: MacOS 10.13.6
neovim version: 0.3.0
SpaceVim version: 0.9.0-dev
This plugin version: 736bbdf

Insert mode in PHP files throws these errors:
```
[deoplete] Traceback (most recent call last):                                                                                                        
  File "/Users/johnnypea/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/child.py", line 250, in _gather_async_results
                                                                                                                                                     
    async_candidates = source.gather_candidates(context)                                                                                             
  File "/Users/johnnypea/.cache/vimfiles/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", l
ine 29, in gather_candidates                                                                                                                         
    candidates = outputs[0].get("result", [])                                                                                                        
AttributeError: 'list' object has no attribute 'get'                                                                                                 
Error from LanguageClient: AttributeError("'list' object has no attribute 'get'").  Use :messages / see above for error details.                     
[deoplete] Traceback (most recent call last):                                                                                                        
  File "/Users/johnnypea/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/child.py", line 250, in _gather_async_results
                                                                                                                                                     
    async_candidates = source.gather_candidates(context)                                                                                             
  File "/Users/johnnypea/.cache/vimfiles/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", l
ine 29, in gather_candidates                                                                                                                         
    candidates = outputs[0].get("result", [])                                                                                                        
AttributeError: 'list' object has no attribute 'get'                                                                                                 
Error from LanguageClient: AttributeError("'list' object has no attribute 'get'").  Use :messages / see above for error details.                     
[deoplete] Too many errors from "LanguageClient". This source is disabled until Neovim is restarted.
```

Anything I can do about it? Thank you!

**Comment by autozimu** [comment]
Please provide minimal vimrc and reproduction steps.

**Comment by autozimu** [comment]
Missing reproduction steps. Closing.
