### ISSUE TITLE
[Bug]Python LSP error  in NeoVim

### ISSUE THREAD

**Issue by TrsNium** [autozimu/LanguageClient-neovim#600]
Hello!
When the change to Insert mode, I got an error as follows.
```
[deoplete] Traceback (most recent call last):
  File "/home/trsnium/.cache/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/child.py", line 250, in _gather_async_results
    async_candidates = source.gather_candidates(context)
  File "/home/trsnium/.cache/dein/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 29, in gather_candidates
    candidates = outputs[0].get("result", [])
AttributeError: 'list' object has no attribute 'get'
Error from LanguageClient: AttributeError("'list' object has no attribute 'get'",).  Use :messages / see above for error details.
```

My set up detail is follows.
OS: ubuntu 18
neovim version:  v0.3.2-dev

python version: Python 3.5.1 :: Anaconda 4.1.0 (64-bit)
packages([neovim](https://github.com/neovim/python-client) and [python-language-server](https://github.com/sourcegraph/python-langserver)) already installed 

and my fragment config file is following.
```neovim.toml
[[plugins]] # 補完
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
on_event = 'InsertEnter'
hook_source = '''
    let g:deoplete#enable_at_startup   = 1
    let g:deoplete#auto_complete_delay = 0
    
    if !has('nvim')
        call dein#add('roxma/nvim-yarp')
        call dein#add('roxma/vim-hug-neovim-rpc')
    endif
    let g:deoplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i  = 1
on_ft = ['snippet']
hook_source = '''
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
if has('conceal')
    set conceallevel=2 concealcursor=niv
endif
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_i = 1
hook_source = '''
imap <expr><TAB>
 \ pumvisible() ? "\<C-n>" :
 \ neosnippet#expandable_or_jumpable() ?
 \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
depends = 'deoplete.nvim'
on_ft = ['python']
build = './install.sh'
hook_source = '''
set hidden
let g:LanguageClient_serverCommands = {
	\ 'python': ['pyls']
}
nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
'''
```

**Comment by autozimu** [comment]
Is there any reason you're using the deprecated master branch and not the current next branch?

**Comment by balta2ar** [comment]
Why next branch is even there? If master is deprecated and not used, why not replace it with next? Wouldn't it be simpler for the end users to just clone and not switch branches?

**Comment by TrsNium** [comment]
@autozimu 
there is not especially reason.

**Comment by autozimu** [comment]
@TrsNium if possible, can you switch to branch next?

**Comment by TrsNium** [comment]
Sure. And I changed.
```toml
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
depends = 'deoplete.nvim'
on_ft = ['python']
rev = 'next'
build = 'install.sh'
hook_source = '''
set hidden
let g:LanguageClient_serverCommands = {
	\ 'python': ['pyls']
}
nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
'''
```

Above error is missing but instead occur new error.
```
[dein] Error occurred while executing hook: LanguageClient-neovim
[dein] Vim(let):E722: Missing comma in Dictionary:
```

**Comment by autozimu** [comment]
I don't know much about dein's toml syntax, but that's definitely not related to the issue originally discussed.

Please try follow the version here https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#deinvim-user

**Comment by TrsNium** [comment]
Sorry, this is my careless miss.
this issue is solved.

```toml
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
on_ft = ['python']
rev = 'next'
build = 'source install.sh'
hook_source = '''
set hidden
let g:LanguageClient_serverCommands = {
	\ 'python': ['pyls']
	\}
nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''

```

Thanks!

**Comment by TamaMcGlinn** [comment]
I think this should be reopened. The fix should either be to downgrade the master to a known working version, or keep it in line with the `next` branch. It doesn't make sense to have a master branch with such a blocking bug on it.
