### ISSUE TITLE
high cpu usage in insert mode while quickfix open

### ISSUE THREAD

**Issue by kwon-young** [autozimu/LanguageClient-neovim#73]
Hello again,
I found something suspicious when toying with the plugin.
I can reproduce the bug for multiple language server.
Step to reproduce the bug:
* open file test.py
* open quickfix window
* go to insert mode in test.py (now the cpu usage of nvim, remote python3 process and the language server spike to 40%, also the neovim screen flickers)
* write something (cpu usage spike to 60-70%)
* quit insert mode, go to the quickfix window (cpu usage return to normal)

- neovim version: 0.2.0
- Plugin version (git SHA): 975c94ca7b31cfc0dbe02e08274a5c7395abb376
- Minimal vimrc:
```
call plug#begin('~/.vim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' }
call plug#end()
let g:deoplete#enable_at_startup = 1
set hidden
" use whatever language server
let g:LanguageClient_serverCommands = {
    \ 'cpp': ['clangd'],
    \ 'python': ['pyls']
    \ }
let g:LanguageClient_autoStart = 1
let g:LanguageClient_trace = 'verbose'
```
- Content of `:CheckHealth`:
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
    /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
    python2.6 not found in search path or not executable.
    /usr/bin/python is Python 3.6 and cannot provide Python 2.
  - ERROR: Python provider error
    - SUGGESTIONS:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.6 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".
```
- Content of `~/.local/share/nvim/rplugin.vim`:
```
" python3 plugins
call remote#host#RegisterPlugin('python3', '/home/vim/.vim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient', [
      \ {'sync': v:true, 'name': 'LanguageClient_alive', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_completionItem/resolve', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_completionManager_refresh', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_exit', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentDocumentSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentReferences', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkWorkspaceSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'BufReadPost', 'type': 'autocmd', 'opts': {'pattern': '*'}},
      \ {'sync': v:false, 'name': 'CursorMoved', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': 'line(''.'')'}},
      \ {'sync': v:false, 'name': 'VimEnter', 'type': 'autocmd', 'opts': {'pattern': '*'}},
      \ {'sync': v:false, 'name': 'LanguageClient_initialize', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_registerServerCommands', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_setLoggingLevel', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClientStart', 'type': 'command', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClientStop', 'type': 'command', 'opts': {}},
      \ {'sync': v:false, 'name': 'TextChanged', 'type': 'autocmd', 'opts': {'pattern': '*'}},
      \ {'sync': v:false, 'name': 'TextChangedI', 'type': 'autocmd', 'opts': {'pattern': '*'}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_completion', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_completionOmnifunc', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_definition', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_didClose', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'BufWritePost', 'type': 'autocmd', 'opts': {'pattern': '*'}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_documentSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_formatting', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_hover', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_references', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_rename', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_signatureHelp', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_workspace_symbol', 'type': 'function', 'opts': {}},
     \ ])
call remote#host#RegisterPlugin('python3', '/home/vim/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete', [
      \ {'sync': v:true, 'name': '_deoplete', 'type': 'function', 'opts': {}},
     \ ])


" ruby plugins


" python plugins
```
- Run `:call LanguageClient_setLoggingLevel('DEBUG')` and then
  `:LanguageClientStart`, reproduce the bug, attach content of
  `/tmp/LanguageClient.log` (the file is 6000 line long for a few second of editing, so i'm gonna just put a part of it):
```
20:21:28 WARNING  Unknown project type. Fallback to use dir as project root.
20:21:29 WARNING  register completion manager source failed. Error: NvimError(b'Error calling function.',)
20:22:29 INFO     textDocument/didChange
20:22:29 DEBUG     => {"jsonrpc":"2.0","params":{"textDocument":{"version":2,"uri":"file:///tmp/test.py"},"contentChanges":[{"text":"import os\n\n"}]},"method":"textDocument/didChange"}
20:22:29 DEBUG     <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"W391 blank line at end of file","source":"pycodestyle","range":{"start":{"character":0,"line":1},"end":{"character":1,"line":1}},"severity":2,"code":"W391"},{"message":"'os' imported but unused","source":"pyflakes","range":{"start":{"character":0,"line":0},"end":{"character":10,"line":0}}}],"uri":"file:///tmp/test.py"}}
20:22:29 INFO     textDocument/didOpen
20:22:29 DEBUG     => {"jsonrpc":"2.0","params":{"textDocument":{"languageId":"python","version":1,"uri":"file:///tmp/test.py","text":"import os\n\n"}},"method":"textDocument/didOpen"}
20:22:29 DEBUG     <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"W391 blank line at end of file","source":"pycodestyle","range":{"start":{"character":0,"line":1},"end":{"character":1,"line":1}},"severity":2,"code":"W391"},{"message":"'os' imported but unused","source":"pyflakes","range":{"start":{"character":0,"line":0},"end":{"character":10,"line":0}}}],"uri":"file:///tmp/test.py"}}
... (repeat a lot)
20:22:29 INFO     Begin textDocument/completion
20:22:29 INFO     textDocument/didChange
20:22:29 INFO     textDocument/didOpen
20:22:29 INFO     textDocument/didChange
20:22:29 DEBUG     => {"jsonrpc":"2.0","params":{"textDocument":{"version":2,"uri":"file:///tmp/test.py"},"contentChanges":[{"text":"import os\no\n"}]},"method":"textDocument/didChange"}
20:22:29 DEBUG     => {"jsonrpc":"2.0","params":{"textDocument":{"languageId":"python","version":1,"uri":"file:///tmp/test.py","text":"import os\no\n"}},"method":"textDocument/didOpen"}
20:22:29 DEBUG     => {"jsonrpc":"2.0","id":1,"params":{"textDocument":{"uri":"file:///tmp/test.py"},"position":{"line":1,"character":1}},"method":"textDocument/completion"}
20:22:29 DEBUG     <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"'os' imported but unused","source":"pyflakes","range":{"start":{"character":0,"line":0},"end":{"character":10,"line":0}}},{"message":"undefined name 'o'","source":"pyflakes","range":{"start":{"character":0,"line":1},"end":{"character":2,"line":1}}}],"uri":"file:///tmp/test.py"}}
20:22:29 DEBUG     <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"'os' imported but unused","source":"pyflakes","range":{"start":{"character":0,"line":0},"end":{"character":10,"line":0}}},{"message":"undefined name 'o'","source":"pyflakes","range":{"start":{"character":0,"line":1},"end":{"character":2,"line":1}}}],"uri":"file:///tmp/test.py"}}
20:22:29 INFO     textDocument/didOpen
20:22:29 INFO     textDocument/didOpen
20:22:29 DEBUG     => {"jsonrpc":"2.0","params":{"textDocument":{"languageId":"python","version":1,"uri":"file:///tmp/test.py","text":"import os\no\n"}},"method":"textDocument/didOpen"}
20:22:29 DEBUG     => {"jsonrpc":"2.0","params":{"textDocument":{"languageId":"python","version":1,"uri":"file:///tmp/test.py","text":"import os\no\n"}},"method":"textDocument/didOpen"}
20:22:30 INFO     textDocument/didChange
20:22:30 DEBUG     => {"jsonrpc":"2.0","params":{"textDocument":{"version":2,"uri":"file:///tmp/test.py"},"contentChanges":[{"text":"import os\nos\n"}]},"method":"textDocument/didChange"}
20:22:30 DEBUG     <= {"id":1,"jsonrpc":"2.0","result":{"isIncomplete":false,"items":[{"label":"object","kind":7,"detail":"class object","sortText":"zobject","documentation":"The most base type"},{"label":"oct","kind":3,"detail":"def oct","sortText":"zoct","documentation":"Return the octal representation of an integer.\n\n>>> oct(342391)\n'0o1234567'"},{"label":"open","kind":3,"detail":"def open","sortText":"zopen","documentation":""},{"label":"ord","kind":3,"detail":"def ord","sortText":"zord","documentation":"Return the Unicode code point for a one-character string."},{"label":"os","kind":9,"detail":"module os","sortText":"aos","documentation":""},{"label":"OSError","kind":7,"detail":"class OSError","sortText":"zOSError","documentation":"Base class for I/O related errors."},{"label":"OverflowError","kind":7,"detail":"class OverflowError","sortText":"zOverflowError","documentation":"Result too large to be represented."}]}}
20:22:30 DEBUG     <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"'os' imported but unused","source":"pyflakes","range":{"start":{"character":0,"line":0},"end":{"character":10,"line":0}}},{"message":"undefined name 'o'","source":"pyflakes","range":{"start":{"character":0,"line":1},"end":{"character":2,"line":1}}}],"uri":"file:///tmp/test.py"}}
20:22:30 DEBUG     <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"'os' imported but unused","source":"pyflakes","range":{"start":{"character":0,"line":0},"end":{"character":10,"line":0}}},{"message":"undefined name 'o'","source":"pyflakes","range":{"start":{"character":0,"line":1},"end":{"character":2,"line":1}}}],"uri":"file:///tmp/test.py"}}
20:22:30 DEBUG     <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///tmp/test.py"}}
... (repeat a lot)
```
is that behavior normal?

**Comment by autozimu** [comment]
Does it happen when using single language server? I believe it is a "NO", just check to confirm on your side.

**Comment by kwon-young** [comment]
no, I've tested with clangd and with python language server and it's happening for both

**Comment by kwon-young** [comment]
After further test, I can reproduce the behaviour for clangd and the python language server: https://github.com/palantir/python-language-server but not for the ruby language server, didn't test the rust language server

**Comment by autozimu** [comment]
I noticed something suspicious. 

The test.py file is in "/tmp" dir, right? If I am right, that will use "/tmp" dir as the project root, which usually contains tons of temporary files, thus the high CPU usage.

**Comment by kwon-young** [comment]
I've reproduced the bug by creating a `test` directory in my home folder (don't know if this will be enough for specifying that directory as the project root ...) and editing the same `test.py` file.
Have you been able to reproduce the bug?

**Comment by autozimu** [comment]
No, I cannot reproduce it.

Could you put the complete log onto pastebin?

**Comment by kwon-young** [comment]
Hope this will do: http://pastebin.ubuntu.com/25069166/

**Comment by autozimu** [comment]
Seems like it keeps sending "didOpen" notification.

Could you change the minimum vimrc a bit to
```
let g:LanguageClient_autoStart = 0
```
and start plugin manually with `:LanguageClientStart`?

**Comment by kwon-young** [comment]
I can reproduce the bug when starting manually the plugin.
It didn't caught my attention until now but sometimes, when I quit insert mode (while the bug is happening) and go to the quickfix window, I can see this error message:
```
"test.py" 4L, 49C

error caught in async handler '/home/vim/.vim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient:autocmd:BufReadPost:* []'
Traceback (most recent call last):

  File "/home/vim/.vim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient/LanguageClient.py", line 345, in handleBufReadPost
    self.textDocument_didOpen()

  File "/home/vim/.vim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient/LanguageClient.py", line 31, in wrappedf
    return f(*fullargs)

  File "/home/vim/.vim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient/LanguageClient.py", line 371, in textDocument_didOpen
    self.rpc[languageId].notify("textDocument/didOpen", {

KeyError: 'qf'
```

**Comment by autozimu** [comment]
The error message is caused by a race condition.

Might be different with your previous seen bug.

**Comment by kwon-young** [comment]
I've tested the fix and everything works smoothly now.
Thanks a lot!
