### ISSUE TITLE
[RLS] Nothing happens on hover

### ISSUE THREAD

**Issue by Ploppz** [autozimu/LanguageClient-neovim#889]
I installed LanguageClient-neovim as in the Quick start page (exact same configuration)

I installed RLS with: `rustup component add rls-preview rust-analysis rust-src`

When I call `:call LanguageClient_contextMenu()` and select "Hover" or "TypeDefinition", nothing happens. Not even a message.

When I select "Implementation" I get `[LC] Error: Failure { jsonrpc: Some(V2), error: Error { code: InternalError, message: "An unknown error occurred", data: None }, id: Num(6) }`.

## Environment
```
$ nvim --version
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- This plugin version (`git rev-parse --short HEAD`): I did not check out git.
- This plugin's binary version (`bin/languageclient --version`): I don't have that binary
- Language server link and version: RLS installed according to https://rls.booyaa.wtf/install/

**Comment by h-michael** [comment]
You can get the language client and server log.
See [this](https://github.com/autozimu/LanguageClient-neovim/blob/next/doc/LanguageClient.txt#L222-L241).
If you show log, it will solve faster. :)

**Comment by Ploppz** [comment]
When trying to hover:
```
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/unicode_xid-319fb29d5faf0853.d","emit":"dep-info"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/semver_parser-c2c505bbd395202a.d","emit":"dep-info"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/save-analysis/libunicode_xid-319fb29d5faf0853.json","emit":"save-analysis"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/cc-f29683721ac677d9.d","emit":"dep-info"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libunicode_xid-319fb29d5faf0853.rmeta","emit":"metadata"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libunicode_xid-319fb29d5faf0853.rlib","emit":"link"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/xml-97e013082930c3ad.d","emit":"dep-info"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/save-analysis/libsemver_parser-c2c505bbd395202a.json","emit":"save-analysis"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libsemver_parser-c2c505bbd395202a.rmeta","emit":"metadata"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/save-analysis/libcc-f29683721ac677d9.json","emit":"save-analysis"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libcc-f29683721ac677d9.rmeta","emit":"metadata"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/save-analysis/libxml-97e013082930c3ad.json","emit":"save-analysis"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libsemver_parser-c2c505bbd395202a.rlib","emit":"link"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libxml-97e013082930c3ad.rmeta","emit":"metadata"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/semver-9b809552ecad2a81.d","emit":"dep-info"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/save-analysis/libsemver-9b809552ecad2a81.json","emit":"save-analysis"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/proc_macro2-15c4e85fadaf5670.d","emit":"dep-info"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libsemver-9b809552ecad2a81.rmeta","emit":"metadata"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libc-645218f787cd2044.d","emit":"dep-info"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/save-analysis/libproc_macro2-15c4e85fadaf5670.json","emit":"save-analysis"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libsemver-9b809552ecad2a81.rlib","emit":"link"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libproc_macro2-15c4e85fadaf5670.rmeta","emit":"metadata"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libxml-97e013082930c3ad.rlib","emit":"link"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/liblibc-645218f787cd2044.rmeta","emit":"metadata"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libcc-f29683721ac677d9.rlib","emit":"link"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/liblibc-645218f787cd2044.rlib","emit":"link"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libproc_macro2-15c4e85fadaf5670.rlib","emit":"link"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/quote-8ae4d4d051e812df.d","emit":"dep-info"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/save-analysis/libquote-8ae4d4d051e812df.json","emit":"save-analysis"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libquote-8ae4d4d051e812df.rmeta","emit":"metadata"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libquote-8ae4d4d051e812df.rlib","emit":"link"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/syn-6d48778afd21c615.d","emit":"dep-info"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/save-analysis/libsyn-6d48778afd21c615.json","emit":"save-analysis"}
{"message":"src/librustc/ty/context.rs:211: node type <B>::Item (hir_id=HirId { owner: DefIndex(246), local_id: 15 }) with HirId::owner DefId(0:246 ~ rayon[3354]::iter[0]::chain[0]::{{impl}}[2]::with_producer[0]::{{impl}}[0]) cannot be placed in TypeckTables with local_id_root DefId(0:238 ~ rayon[3354]::iter[0]::chain[0]::{{impl}}[2]::with_producer[0])","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":"error: internal compiler error: src/librustc/ty/context.rs:211: node type <B>::Item (hir_id=HirId { owner: DefIndex(246), local_id: 15 }) with HirId::owner DefId(0:246 ~ rayon[3354]::iter[0]::chain[0]::{{impl}}[2]::with_producer[0]::{{impl}}[0]) cannot be placed in TypeckTables with local_id_root DefId(0:238 ~ rayon[3354]::iter[0]::chain[0]::{{impl}}[2]::with_producer[0])\n\n"}
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:643:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  12: std::panicking::begin_panic
  13: rustc_errors::Handler::bug
  14: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  15: rustc::ty::context::tls::with_opt::{{closure}}
  16: rustc::ty::context::tls::with_context_opt
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: rustc::ty::context::validate_hir_id_for_typeck_tables::{{closure}}
  21: rustc::ty::context::tls::with::{{closure}}
  22: rustc::ty::context::tls::with_context::{{closure}}
  23: rustc::ty::context::tls::with_context_opt
  24: rustc::ty::context::tls::with_context
  25: rustc::ty::context::tls::with
  26: rustc::ty::context::TypeckTables::qpath_res
  27: rustc_save_analysis::SaveContext::get_path_res
  28: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_ty
  29: rustc_save_analysis::dump_visitor::DumpVisitor::process_path
  30: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  31: rustc_save_analysis::dump_visitor::DumpVisitor::process_method::{{closure}}
  32: rustc_save_analysis::dump_visitor::DumpVisitor::process_method
  33: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  34: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  35: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  36: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_mod
  37: rustc::dep_graph::graph::DepGraph::with_ignore
  38: rustc_driver::run_compiler::{{closure}}::{{closure}}::{{closure}}
  39: rustc::util::common::time
  40: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  41: rustc_interface::passes::create_global_ctxt::{{closure}}
  42: rustc_interface::interface::run_compiler_in_existing_thread_pool
  43: std::thread::local::LocalKey<T>::with
  44: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0-nightly (eceec57f7 2019-09-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libsyn-6d48778afd21c615.rmeta","emit":"metadata"}
{"artifact":"/home/ploppz/code/gui/target/rls/debug/deps/libsyn-6d48778afd21c615.rlib","emit":"link"}
```

I also tried with `:let g:LanguageClient_loggingLevel = 'DEBUG'` but then I got nothing.

**Comment by h-michael** [comment]
@Ploppz I think that is not LanguageClient-neovim issue but rls or rustc issue.

**Comment by Ploppz** [comment]
Ok, thanks
